name: deploy-website

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: install node.js
        uses: actions/setup-node@v3.0.0
        with:
          node-version: "14.x"
      - name: install deps
        run: yarn install
      - name: build app
        run: yarn build
      - name: copy dist file with scp
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USERNAME }}
          password: ${{ secrets.REMOTE_PASSWORLD }}
          port: 22
          source: "docs/"
          target: ${{ secrets.REMOTE_TARGET }}
